### ISSUE TITLE
Cutoff navigation on mobil screen

### ISSUE THREAD

**Issue by Coffeeri** [mehdihadeli/awesome-software-architecture#28]
Hello!
First,  thank you for creating this awesome-page! @mehdihadeli 

I've noticed that you added some custom CSS in `docs/static/extra.css`
Commit: 8c56bca733de9b10d0a67d268182282ca61bc86e

```css
.md-content {
  margin-left: 14.1rem;
}

.md-sidebar {
  position: absolute;
  width: 14.1rem;
  padding: 1.2rem 0;
  overflow: hidden;
}
```

These changes make the page unusable on mobile screens such as phones.
I am not sure what you were trying to archive with this custom CSS, let me know if I can help you with that.
Screenshot:
![Screenshot](https://user-images.githubusercontent.com/8344540/122091572-39855900-ce09-11eb-9497-1851aac21faa.png)
